// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRYtij2DVlmRJ_QftJRESwUy66NhZifnQ',
    appId: '1:927858756788:web:28fa091acd16d119c91be1',
    messagingSenderId: '927858756788',
    projectId: 'overidea-assignment',
    authDomain: 'overidea-assignment.firebaseapp.com',
    storageBucket: 'overidea-assignment.appspot.com',
    measurementId: 'G-S4ZMY16VL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYEVbxfPfFMP7_jTnpcxuK2L2T7MQ5oRk',
    appId: '1:927858756788:android:2eb0f2521e44c7f4c91be1',
    messagingSenderId: '927858756788',
    projectId: 'overidea-assignment',
    storageBucket: 'overidea-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzcu0QfdnWh7n_B8Ruiubu6qGWTCCBHWg',
    appId: '1:927858756788:ios:c1d9f9c6b20ebfa7c91be1',
    messagingSenderId: '927858756788',
    projectId: 'overidea-assignment',
    storageBucket: 'overidea-assignment.appspot.com',
    iosBundleId: 'com.example.overideaAssignment',
  );
}
